version: '2'
services:
    elasticsearch:
        image: 84b89281aa1d
        environment:
            ELASTIC_PWD: changeme
            KIBANA_PWD: brucewayne
        volumes:
            - /data/elasticsearch:/usr/share/elasticsearch/data
            - /etc/elasticsearch:/usr/share/elasticsearch/config
        ports:
             - "9200:9200"
             - "9300:9300"
        network_mode: bridge
        restart: always

    